version: '3.8'

services:
  # Serveur MCP principal
  mcp_server:
    build: ./serveur_mcp
    container_name: mcp_server
    ports:
      - "8080:8080"
    volumes:
      - ./serveur_mcp:/app
      - ./llm:/app/llm
      - ./memoire:/app/memoire
      - ./speech:/app/speech
      - ./vision:/app/vision
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/robot_mignon
      - LLM_ENGINE=llama3
      - LLM_MODEL_PATH=/app/llm/models
      - ROBOT_ID=MignonBot1
    restart: unless-stopped

  # Base de données pour stocker l'historique et la mémoire
  database:
    image: postgres:14
    container_name: mcp_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=robot_mignon
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Interface web pour visualiser l'état du robot et interagir
  web_interface:
    build: ./interface
    container_name: mcp_web_interface
    ports:
      - "8000:8000"
    volumes:
      - ./interface:/app
    depends_on:
      - mcp_server
    environment:
      - MCP_SERVER_URL=http://mcp_server:8080
    restart: unless-stopped

  # Service de reconnaissance et synthèse vocale
  speech_service:
    build: ./speech
    container_name: mcp_speech
    volumes:
      - ./speech:/app
    depends_on:
      - mcp_server
    environment:
      - MCP_SERVER_URL=http://mcp_server:8080
    restart: unless-stopped

  # Service de vision par ordinateur
  vision_service:
    build: ./vision
    container_name: mcp_vision
    volumes:
      - ./vision:/app
    depends_on:
      - mcp_server
    environment:
      - MCP_SERVER_URL=http://mcp_server:8080
    restart: unless-stopped

volumes:
  db_data:
